### ISSUE TITLE
Export feature, Getting crash in the Android

### ISSUE THREAD

**Issue by TarunDholakiyaClarion** [highcharts/highcharts-android#113]
Recently, I have downloaded the Demo of the HighChart from the HighChart Android Github page. I have tried to export the chart by clicking on the hamburger icon. But it never worked. Getting crash every time.

`2019-09-05 17:39:28.453 28060-28060/com.highsoft.highfit E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.highsoft.highfit, PID: 28060
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
    at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
    at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
    at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
    at com.highsoft.highcharts.core.e.onDownloadStart(SourceFile:63)
    at uU.a(PG:532)
    at aIV.handleMessage(PG:25)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6762)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

Note: I have already allowed the storage permission.

Does anyone else come across this issue? Any help, hint, suggestions are welcome. Thanks in advance.

**Comment by soommy12** [comment]
Hi, hello for your report. I will investigate.

**Comment by TarunDholakiyaClarion** [comment]
Hi, I have tested by uncommenting the provider tags in manifest and it worked. 
Can you please confirm that the export feature is compatible with AndroidX.
As I am using "androidx.core.content.FileProvider".

**Comment by soommy12** [comment]
Yes, it does work :)

**Comment by fasi1208** [comment]
Below is provider 

`<provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="com.thumbsol.accuratemobileassetsmanagament"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>`
        
        Below is my path
        
        `<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">

    <external-path name="my_images" path="Android/data/com.thumbsol.accuratemobileassetsmanagament/files/Pictures" />
    <external-path name="my_download" path="Android/data/com.thumbsol.accuratemobileassetsmanagament/files/Download" />

</paths>`

But still my app crashes :(
