### ISSUE TITLE
HIOptions Not Found in HIChartView

### ISSUE THREAD

**Issue by adirahman** [highcharts/highcharts-android#12]
here's the error code:

 Process: monitoring_analytic.test.com, PID: 22751
    java.util.NoSuchElementException: HIOptions not found in HIChartView
        at com.highsoft.highcharts.Core.HIChartView.a(SourceFile:262)
        at com.highsoft.highcharts.Core.HIChartView.a(SourceFile:190)
        at com.highsoft.highcharts.Core.HIChartView.onDraw(SourceFile:182)
        at android.view.View.draw(View.java:17211)
        at android.view.View.updateDisplayListIfDirty(View.java:16193)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.updateDisplayListIfDirty(View.java:16188)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
        at android.view.View.updateDisplayListIfDirty(View.java:16188)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.updateDisplayListIfDirty(View.java:16188)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.updateDisplayListIfDirty(View.java:16188)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.updateDisplayListIfDirty(View.java:16188)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.updateDisplayListIfDirty(View.java:16188)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.draw(View.java:17214)
        at com.android.internal.policy.DecorView.draw(DecorView.java:757)
        at android.view.View.updateDisplayListIfDirty(View.java:16193)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2842)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2650)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2257)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1296)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6401)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
        at android.view.Choreographer.doCallbacks(Choreographer.java:688)
        at android.view.Choreographer.doFrame(Choreographer.java:623)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6361)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by soommy12** [comment]
Hi @adirahman ,
please attach `HIOptions` object to your chart. Chart view cannot exist without chart options.
```
HIChartView chartView = findViewById(R.id.hc);
HIOptions options = new HIOptions();
//set up your options
chartView.setOptions(options);
```

**Comment by adirahman** [comment]
thank's, i not set the options, before get data from network request.
It's already fixed, thank's
