### ISSUE TITLE
java.util.NoSuchElementException: HIOptions not found in HIChartView

### ISSUE THREAD

**Issue by DikshantYadav19** [highcharts/highcharts-android#15]
HIChartView chartView =  dialog.findViewById(R.id.hc);

                HIOptions options = new HIOptions();

                HIChart chart = new HIChart();
                chart.setType("column");
                options.setChart(chart);

                HITitle title = new HITitle();
                title.setText("Demo chart");
                options.setTitle(title);

                HIColumn series = new HIColumn();
                series.setData(new ArrayList<>(Arrays.asList(49.9, 71.5, 106.4, 129.2, 144, 176, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4)));
                options.setSeries(new ArrayList<HISeries>(Collections.singletonList(series)));

                chartView.setOptions(options);

**Comment by DikshantYadav19** [comment]
java.util.NoSuchElementException: HIOptions not found in HIChartView
                      at com.highsoft.highcharts.Core.HIChartView.a(SourceFile:262)
                      at com.highsoft.highcharts.Core.HIChartView.a(SourceFile:190)
                      at com.highsoft.highcharts.Core.HIChartView.onDraw(SourceFile:182)
                      at android.view.View.draw(View.java:17083)
                      at android.view.View.updateDisplayListIfDirty(View.java:16065)
                      at android.view.View.draw(View.java:16849)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
                      at android.view.View.updateDisplayListIfDirty(View.java:16060)
                      at android.view.View.draw(View.java:16849)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
                      at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
                      at android.view.View.draw(View.java:17086)
                      at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
                      at android.view.View.updateDisplayListIfDirty(View.java:16065)
                      at android.view.View.draw(View.java:16849)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
                      at android.view.View.updateDisplayListIfDirty(View.java:16060)
                      at android.view.View.draw(View.java:16849)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
                      at android.view.View.updateDisplayListIfDirty(View.java:16060)
                      at android.view.View.draw(View.java:16849)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
                      at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1254)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
                      at android.view.View.draw(View.java:17086)
                      at android.view.View.updateDisplayListIfDirty(View.java:16065)
                      at android.view.View.draw(View.java:16849)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
                      at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1366)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
                      at android.view.View.draw(View.java:17086)
                      at android.view.View.updateDisplayListIfDirty(View.java:16065)
                      at android.view.View.draw(View.java:16849)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
                      at android.view.View.updateDisplayListIfDirty(View.java:16060)
                      at android.view.View.draw(View.java:16849)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
                      at android.view.View.updateDisplayListIfDirty(View.java:16060)
                      at android.view.View.draw(View.java:16849)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
                      at android.view.View.updateDisplayListIfDirty(View.java:16060)
                      at android.view.View.draw(View.java:16849)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
                      at android.view.View.updateDisplayListIfDirty(View.java:16060)
                      at android.view.View.draw(View.java:16849)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3554)
                      at android.view.View.draw(View.java:17086)
                      at com.android.internal.policy.DecorView.draw(DecorView.java:751)
                      at android.view.View.updateDisplayListIfDirty(View.java:16065)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:657)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:663)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:771)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2808)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2616)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2223)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                      at android.view.Choreographer.doFrame(Choreographer.java:619)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6123)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by soommy12** [comment]
Hello @DikshantYadav19 ,
can you provide code where exactly you are using this `dialog` ? Is this custom dialog layout?

**Comment by DikshantYadav19** [comment]
This is the code for the dialog layout.            
            
            final LayoutInflater inflater = getLayoutInflater();
            final View alertLayout = inflater.inflate(R.layout.empty_class, null);
            AlertDialog.Builder alert = new AlertDialog.Builder(ViewMarks.this);
            alert.setTitle("Graph");
            alert.setView(alertLayout);
            alert.setCancelable(false);

            alert.setNegativeButton("Cancel", (dialog, which) -> Toast.makeText(getBaseContext(), "Cancel clicked", Toast.LENGTH_SHORT).show());
            alert.setPositiveButton("Done", (dialog, which) -> Toast.makeText(getBaseContext(), "Done click", Toast.LENGTH_SHORT).show());

            AlertDialog dialog = alert.create();
            dialog.show();

**Comment by soommy12** [comment]
Thanks for the snippet. Your options for the chart are set in the wrong place. After a simple layout inflation, the Higcharts library cannot find its options. You should get **HIChartView** instance from your _alertLayout_ like this:
`HIChartView chartView = alertLayout.findViewById(R.id.hc);`
then set needed options. The final step will be building your **dialog**. Your code should look like this (composed from your both snippets):

```
        final LayoutInflater inflater = getLayoutInflater();
        final View alertLayout = inflater.inflate(R.layout.empty_class, null);

//First get your chartView from the inflated view
            HIChartView chartView = alertLayout.findViewById(R.id.hc);
            HIOptions options = new HIOptions();

            HIChart chart = new HIChart();
            chart.setType("column");
            options.setChart(chart);

            HITitle title = new HITitle();
            title.setText("Demo chart");
            options.setTitle(title);

            HIColumn series = new HIColumn();
            series.setData(new ArrayList<>(Arrays.asList(49.9, 71.5, 106.4, 129.2, 144, 176, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4)));
            options.setSeries(new ArrayList<HISeries>(Collections.singletonList(series)));

            chartView.setOptions(options);

//Now you can start building your dialog
        AlertDialog.Builder alert = new AlertDialog.Builder(ViewMarks.this);
        alert.setTitle("Graph");
        alert.setView(alertLayout);
        alert.setCancelable(false);

        alert.setNegativeButton("Cancel", (dialog, which) -> Toast.makeText(getBaseContext(), "Cancel clicked", Toast.LENGTH_SHORT).show());
        alert.setPositiveButton("Done", (dialog, which) -> Toast.makeText(getBaseContext(), "Done click", Toast.LENGTH_SHORT).show());

        AlertDialog dialog = alert.create();
        dialog.show();
```

**Comment by DikshantYadav19** [comment]
But now I have a different problem. A hamburger icon appears on the chart and when I click on that the app crashes. This is the error I get.
                                 `                  java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                      at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
                      at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
                      at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
                      at com.highsoft.highcharts.Core.d.onDownloadStart(SourceFile:64)
                      at xf.a(SourceFile:547)
                      at afs.handleMessage(SourceFile:25)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6123)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
`

`
![screenshot_20180905-195243](https://user-images.githubusercontent.com/17436526/45099868-f1a85200-b145-11e8-97cd-3e2e62f79280.png)

**Comment by soommy12** [comment]
This is an export feature. If you want exporting enabled please configure your project like its said in [this](https://github.com/highcharts/highcharts-android/blob/master/README.md#export-module-requirements) readme section. In the other case disable exporting:
```
        options.setExporting(new HIExporting());
        options.getExporting().setEnabled(false);
```

**Comment by sarfaraz175** [comment]
java.util.NoSuchElementException: HIOptions not found in HIChartView
        at com.highsoft.highcharts.core.HIChartView.a(SourceFile:277)
        at com.highsoft.highcharts.core.HIChartView.a(SourceFile:204)
        at com.highsoft.highcharts.core.HIChartView.onDraw(SourceFile:196)
        at android.view.View.draw(View.java:17526)
        at android.view.View.updateDisplayListIfDirty(View.java:16519)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.updateDisplayListIfDirty(View.java:16514)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.draw(View.java:17529)
        at android.widget.ScrollView.draw(ScrollView.java:2778)
        at android.view.View.updateDisplayListIfDirty(View.java:16519)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.draw(View.java:17529)
        at android.view.View.updateDisplayListIfDirty(View.java:16519)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.updateDisplayListIfDirty(View.java:16514)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.draw(View.java:17529)
        at android.view.View.updateDisplayListIfDirty(View.java:16519)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.draw(View.java:17529)
        at android.view.View.updateDisplayListIfDirty(View.java:16519)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.draw(View.java:17529)
        at android.view.View.updateDisplayListIfDirty(View.java:16519)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.updateDisplayListIfDirty(View.java:16514)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.updateDisplayListIfDirty(View.java:16514)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.updateDisplayListIfDirty(View.java:16514)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.updateDisplayListIfDirty(View.java:16514)
        at android.view.View.draw(View.java:17295)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3926)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3716)
        at android.view.View.draw(View.java:17529)
        at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:3187)
        at android.view.View.updateDisplayListIfDirty(View.java:16519)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3234)
    	at android.view.ViewRootImpl.perfor

**Comment by sarfaraz175** [comment]
Here is my code

HIChartView chartView = findViewById(R.id.hc);
        HIOptions options = new HIOptions();

        HIChart chart = new HIChart();
        chart.setType("column");
        options.setChart(chart);

        HITitle title = new HITitle();
        title.setText("Monthly Closed Bidding Info..");
        options.setTitle(title);

        HISubtitle subtitle = new HISubtitle();
        subtitle.setText("https://www.rampwms.com/");
        options.setSubtitle(subtitle);

        final HIYAxis yAxis = new HIYAxis();
        yAxis.setMin(0);
        yAxis.setTitle(new HITitle());
        yAxis.getTitle().setText("Values");
        options.setYAxis(new ArrayList<HIYAxis>(){{add(yAxis);}});
        //chartView.setOptions(options);

        try
        {
            JSONObject jsonObject=new JSONObject(getIntent().getStringExtra("jsonobj"));
            Log.i("JsonResss",""+jsonObject);
            JSONArray monthBiddingArray=jsonObject.getJSONArray("monthBiddingDetais");
            JSONArray totalClosedBiddingDetail=jsonObject.getJSONArray("totalClosedBiddingDetail");
            JSONArray toptenSparesArray=jsonObject.getJSONArray("toptenBiddingSpare");
            JSONArray totalClosedArray=jsonObject.getJSONArray("totalClosedBiddingInfoDt");
            JSONArray totalDeliveredArray=jsonObject.getJSONArray("totalDeliverdBiddingInfoDt");
            String ttlCancel=jsonObject.getString("totalCancelled");
            cancleCount.setText(ttlCancel);
            categoriesList = new String[monthBiddingArray.length()];
            closeData=new Number[totalClosedBiddingDetail.length()];

            for (int i=0;i<monthBiddingArray.length();i++)
            {
                JSONObject obj=monthBiddingArray.getJSONObject(i);
                String bidDate=obj.getString("biddingDate");
                categoriesList[i]=bidDate;
                biddingDateList.add(bidDate);
            }

            for (int i=0;i<totalClosedBiddingDetail.length();i++)
            {
                JSONObject obj=totalClosedBiddingDetail.getJSONObject(i);
                if (DataValidation.isNullString(obj.getString("vendorRate")))
                    vendorRate=0;
                else
                    vendorRate=Integer.parseInt(obj.getString("vendorRate"));

                closeData[i]=vendorRate;
            }




            final HIXAxis xAxis = new HIXAxis();
            String[] categoriesList = new String[] {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
            xAxis.setCategories(new ArrayList<>(Arrays.asList(categoriesList)));
            xAxis.setCrosshair(new HICrosshair());
            options.setXAxis(new ArrayList<HIXAxis>(){{add(xAxis);}});

            HITooltip tooltip = new HITooltip();
            tooltip.setHeaderFormat("<span style=\"font-size:10px\">{point.key}</span><table>");
            tooltip.setPointFormat("<tr><td style=\"color:{series.color};padding:0\">{series.name}: </td><td style=\"padding:0\"><b>{point.y:.1f} mm</b></td></tr>");
            tooltip.setFooterFormat("</table>");
            tooltip.setShared(true);
            tooltip.setUseHTML(true);
            options.setTooltip(tooltip);

            HIPlotOptions plotOptions = new HIPlotOptions();
            plotOptions.setColumn(new HIColumn());
            plotOptions.getColumn().setPointPadding(0.2);
            plotOptions.getColumn().setBorderWidth(0);
            options.setPlotOptions(plotOptions);

            HIColumn series1 = new HIColumn();
            series1.setName("Close");
            Number[] series1_data = new Number[] {49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4};
            series1.setData(new ArrayList<>(Arrays.asList(series1_data)));

            HIColumn series2 = new HIColumn();
            series2.setName("Delivered");
            Number[] series2_data = new Number[] {83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3};
            series2.setData(new ArrayList<>(Arrays.asList(series2_data)));

            options.setSeries(new ArrayList<HISeries>(Arrays.asList(series1,series2)));

            chartView.setOptions(options);
 }
        catch (Exception e)
        {

        }
