### ISSUE TITLE
ArrayIndexOutOfBoundsException triggered by internal call to Gson causes HICharts to crash

### ISSUE THREAD

**Issue by mardann** [highcharts/highcharts-android#154]
this seems to happen when applying `categories` to `xAxis`, or applying `data` array to whatever `series`- so when applying and `ArrayList` of some sort.
What's weird - this crash happens when installing the app with an .APK (debug or release) file, but **NOT** when loading the app directly from _Android Studio_

- the app uses `com.highsoft.highcharts:highcharts:8.1.2` and `com.google.code.gson:gson:2.8.0`
- using kotlin
- Particular HIChart views are implemented as custom `Views` inheriting from an _intermediary class_*, that inherits from the base `HIChartView` (example in attached file
[LineGraphChart.tk.txt](https://github.com/highcharts/highcharts-android/files/4999436/LineGraphChart.tk.txt)
)
- this _intermediary class_ I called `SafeHIChartsView` is needed to provide compatibility with `Hilt` DI ,as I posted in issue #153 

this is the relevant stacktrace (the _hours_ are the categories being set):
```
2020-07-30 09:39:25.640 5627-5627/com.app.android.debug E/HINativeController: [
      "13:30",
      "13:35",
      "13:40",
      "13:45",
      "13:50",
      "13:55",
      "14:00",
      "14:05",
      "14:10",
      "14:15",
      "14:20",
      "14:25",
      "14:30",
      "14:35",
      "14:40",
      "14:45",
      "14:50",
      "14:55",
      "15:00",
      "15:05",
      "15:10",
      "15:15",
      "15:20",
      "15:25",
      "15:30",
      "15:35",
      "15:40",
      "15:45",
      "15:50",
      "15:55",
      "16:00",
      "16:05",
      "16:10",
      "16:15",
      "16:20",
      "16:25",
      "16:30",
      "16:35",
      "16:40",
      "16:45",
      "16:50",
      "16:55",
      "17:00",
      "17:05",
      "17:10",
      "17:15",
      "17:20",
      "17:25",
      "17:30",
      "17:35",
      "17:40",
      "17:45",
      "17:50",
      "17:55",
      "18:00",
      "18:05",
      "18:10",
      "18:15",
      "18:20",
      "18:25",
      "18:30",
      "18:35",
      "18:40",
      "18:45",
      "18:50",
      "18:55",
      "19:00",
      "19:05",
      "19:10",
      "19:15",
      "19:20",
      "19:25",
      "19:30",
      "19:35",
      "19:40",
      "19:45",
      "19:50",
      "19:55",
      "20:00"
    ]
2020-07-30 09:39:25.661 5627-5627/com.app.android.debug E/HIChartView: javascript:(function setCategories(axis, wrapperID, categories) { switch(axis) { case "x": chart.xAxis.forEach(function(currentAxis){ if (currentAxis.options._wrapperID === wrapperID) { currentAxis.setCategories(categories); return; } }); break; case "y": chart.yAxis.forEach(function(currentAxis){ if (currentAxis.options._wrapperID === wrapperID) { currentAxis.setCategories(categories); return; } }); break; case "z": chart.zAxis.forEach(function(currentAxis){ if (currentAxis.options._wrapperID === wrapperID) { currentAxis.setCategories(categories); return; } }); break; default: return; } })("x", "94eea651-0a01-408c-9d84-b910bd0f8a1b", [
      "13:30",
      "13:35",
      "13:40",
      "13:45",
      "13:50",
      "13:55",
      "14:00",
      "14:05",
      "14:10",
      "14:15",
      "14:20",
      "14:25",
      "14:30",
      "14:35",
      "14:40",
      "14:45",
      "14:50",
      "14:55",
      "15:00",
      "15:05",
      "15:10",
      "15:15",
      "15:20",
      "15:25",
      "15:30",
      "15:35",
      "15:40",
      "15:45",
      "15:50",
      "15:55",
      "16:00",
      "16:05",
      "16:10",
      "16:15",
      "16:20",
      "16:25",
      "16:30",
      "16:35",
      "16:40",
      "16:45",
      "16:50",
      "16:55",
      "17:00",
      "17:05",
      "17:10",
      "17:15",
      "17:20",
      "17:25",
      "17:30",
      "17:35",
      "17:40",
      "17:45",
      "17:50",
      "17:55",
      "18:00",
      "18:05",
      "18:10",
      "18:15",
      "18:20",
      "18:25",
      "18:30",
      "18:35",
      "18:40",
      "18:45",
      "18:50",
      "18:55",
      "19:00",
      "19:05",
      "19:10",
      "19:15",
      "19:20",
      "19:25",
      "19:30",
      "19:35",
      "19:40",
      "19:45",
      "19:50",
      "19:55",
      "20:00"
    ]);
2020-07-30 09:39:25.679 5627-5627/com.app.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.android.debug, PID: 5627
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.google.gson.internal.$Gson$Types.getGenericSupertype($Gson$Types.java:240)
        at com.google.gson.internal.$Gson$Types.getSupertype($Gson$Types.java:272)
        at com.google.gson.internal.$Gson$Types.getCollectionElementType($Gson$Types.java:290)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
        at com.google.gson.Gson.getAdapter(Gson.java:423)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
        at com.google.gson.Gson.toJson(Gson.java:669)
        at com.google.gson.Gson.toJson(Gson.java:648)
        at com.google.gson.Gson.toJson(Gson.java:603)
        at com.google.gson.Gson.toJson(Gson.java:583)
        at com.highsoft.highcharts.core.i.a(SourceFile:8)
        at com.highsoft.highcharts.core.f.c(SourceFile:2)
        at com.highsoft.highcharts.core.HIChartView$q0.update(SourceFile:4)
        at java.util.Observable.notifyObservers(Observable.java:163)
        at java.util.Observable.notifyObservers(Observable.java:115)
        at com.highsoft.highcharts.core.HIFoundation$a.update(SourceFile:4)
        at java.util.Observable.notifyObservers(Observable.java:163)
        at java.util.Observable.notifyObservers(Observable.java:115)
        at com.highsoft.highcharts.common.hichartsclasses.HISeries.setData(SourceFile:3)
        at com.app.android.ui.customviews.hicharts.LineGraphChart$applyDataSet$1.run(LineGraphChart.kt:256)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by soommy12** [comment]
Hi @mardann, thanks for the question and sorry for the late response. To be honest I cannot reproduce this problem. It can be connected directly with your wrapper class `SafeHighchartsView`. When it comes to axis type, you can read [this part of our documentation](https://www.highcharts.com/docs/chart-concepts/axes#what-axis-type-should-i-use) which can be helpful.

**Comment by mardann** [comment]
Hey @soommy12, can I send you an .APK/ so you can reproduce on your own? Or, can I have the source code (not the .AAR file), so I can properly debug myself?
I don't think this issue is due to API implementations - as HighCharts works as desired under certain build. Also, the same charts are implemented in our existing iOS app. 

The core of the problem is that something _changes_ from installing directly form the IDE to device/emulator (clicking `Run`), to when manually building (`Make project`) and installing. **The build is different** somehow. The latter breaks.

But I can't figure out what that difference could possibly be? and the stacktrace provides no clues, besides that its somewhere between `Highcharts` and `GSON`

**Comment by soommy12** [comment]
Hi @mardann! Unfortunately, we cannot share the source code. Please, provide a sample project where you facing the issue. My first guess is that in your own build you are obfuscating some irrelevant code (e.g. by proguard or another tool) and you are removing the gson from the project by an accident.

**Comment by mardann** [comment]
Hi @soommy12!

Please contact me here hanan.dann@tipranks.com, so I can share code privately.

I also though it might have to do with ProGuard but: (a) this also happens in `debug` build, where ProGuard isn't run, and (b) I also tested with `keeping` everything `Gson` and `HICharts` with no change in results.

**Comment by soommy12** [comment]
You can find my email in my GitHub profile. Please use it to share the code. When it comes to ProGuard - it is interesting, I definitely need to look at your build configuration.

**Comment by mardann** [comment]
@soommy12, HiCharts just crashed again, but with a different stacktrace. I don't know if this is related to the above issue, but it looks more informative.
I didn't make any changes to my implementation to make this happen.
```
2020-08-16 11:29:11.900 9893-9893/com.app.android.debug E/HIChartView: javascript:(function update(options, redraw) { chart.update(options, redraw); })({
      "plotOptions": {
        "area": {
          "fillColor": {
            "linearGradient": {
              "y1": 0.0,
              "x1": 0.0,
              "y2": 1.0,
              "x2": 0.0
            },
            "stops": [
              [
                0.0,
                "#518513"
              ],
              [
                1.0,
                "#2a2b2d"
              ]
            ]
          },
          "_wrapperID": "389be907-f58c-4eae-a017-5ef95789d22b",
          "marker": {
            "fillColor": "#84d325",
            "_wrapperID": "9499b955-bb62-4b9d-b0e5-fbd2b433466a",
            "lineColor": "#84d325",
            "enabled": false
          },
          "type": "area",
          "lineWidth": 1.5
        },
        "_wrapperID": "054883e8-2a58-45c9-b4db-f2a3da2da132"
      },
      "yAxis": [
        {
          "gridLineColor": "#3b3b3b",
          "min": 452.51,
          "visible": true,
          "_wrapperID": "0cb00b5e-a041-4be9-bf4e-a5170f2a6cd0",
          "max": 459.845,
          "opposite": true,
          "title": {
            "_wrapperID": "8a218c5a-e805-4c42-917b-04c97aa8718c",
            "text": ""
          },
          "labels": {
            "formatter": function() { result = this.value; if (this.value > 1000000000) { result = (this.value / 1000000000).toFixed(2) + 'B' } else if (this.value > 1000000) { result = (this.value / 1000000).toFixed(2) + 'M' } else if (this.value > 1000) { result = (this.value / 1000).toFixed(2) + 'k' } return result + ''; },
            "_wrapperID": "ec99060d-f95e-4716-b14c-75d0671fbc93",
            "useHTML": true
          }
        }
      ],
      "exporting": {
        "_wrapperID": "a030a4b0-0164-4157-bd8c-d2e7b75f69dc",
        "enabled": false
      },
      "xAxis": [
        {
          "_wrapperID": "05f082e2-d35d-4d5f-ab01-e88a0cf9d58b",
          "tickColor": "rgba(0, 0, 0, 0.0)",
          "lineColor": {
            "linearGradient": {
              "y1": 0.0,
              "x1": 0.0,
              "y2": 1.0,
              "x2": 0.0
            },
            "stops": [
              [
                0.0,
                "#8a8a8a"
              ],
              [
                1.0,
                "#000000"
              ]
            ]
          },
          "categories": [
            "13:30",
            "13:35",
            "13:40",
            "13:45",
            "13:50",
            "13:55",
            "14:00",
            "14:05",
            "14:10",
            "14:15",
            "14:20",
            "14:25",
            "14:30",
            "14:35",
            "14:40",
            "14:45",
            "14:50",
            "14:55",
            "15:00",
            "15:05",
            "15:10",
            "15:15",
            "15:20",
            "15:25",
            "15:30",
            "15:35",
            "15:40",
            "15:45",
            "15:50",
            "15:55",
            "16:00",
            "16:05",
            "16:10",
            "16:15",
            "16:20",
            "16:25",
            "16:30",
            "16:35",
            "16:40",
            "16:45",
            "16:50",
            "16:55",
            "17:00",
            "17:05",
            "17:10",
            "17:15",
            "17:20",
            "17:25",
            "17:30",
            "17:35",
            "17:40",
            "17:45",
            "17:50",
            "17:55",
            "18:00",
            "18:05",
            "18:10",
            "18:15",
            "18:20",
            "18:25",
            "18:30",
            "18:35",
            "18:40",
            "18:45",
            "18:50",
            "18:55",
            "19:00",
            "19:05",
            "19:10",
            "19:15",
            "19:20",
            "19:25",
            "19:30",
            "19:35",
            "19:40",
            "19:45",
            "19:50",
            "19:55",
            "20:00"
          ],
          "type": "datetime",
          "labels": {
            "_wrapperID": "f9cb57db-ff4b-494b-8b6b-11274388f4c4",
            "step": 26,
            "enabled": true
          }
        }
      ],
      "credits": {
        "_wrapperID": "9d79b91a-f7ce-43eb-baea-3da79dab1eb2",
        "enabled": false
      },
      "series": [
        {
          "_wrapperID": "2e922b17-f6e5-44ad-a44b-5b22cab65780",
          "data": [
            456.69,
            457.85,
            456.975,
            454.53,
            455.11,
            455.52,
            454.91,
            455.422,
            454.9387,
            454.44,
            454.64,
            453.38,
            453.85,
            454.5,
            454.86,
            454
2020-08-16 11:29:11.906 9893-9893/com.app.android.debug E/HIChartView: javascript:(function resetSonifyCursor() { chart.resetSonifyCursor(); })();
2020-08-16 11:29:11.907 9893-9893/com.app.android.debug D/StatsAndChartsFragment: chartStockPerformance: isBeingTouched? = false  
2020-08-16 11:29:11.907 9893-9893/com.app.android.debug D/StockDetailFragemnt: onMessageEvent: false
2020-08-16 11:29:12.062 9893-9893/com.app.android.debug E/Highcharts: Uncaught TypeError: chart.resetSonifyCursor is not a function
```

**Comment by soommy12** [comment]
This is a javascript function injected to your chart which causes the problem. Do you use sonify in your project?

**Comment by mardann** [comment]
We do not implement any sonification explicitly in our code. Is this something emerging from the JS layer? 
the only `function` injections we do are for formatting labels and sorts. 
These same injections are also performed in the iOS app.
a. what do we need to do to fix this (sonifications) error?
b. is this related to the main issue (indexOutOfBounds)?

**Comment by soommy12** [comment]
@mardann The stacktrace claims that there is a problem with sonify method and the error is coming directly from the JS layer. Is this error occurring during the initialization or during some chart evaluation?

**Comment by mardann** [comment]
Hey- this crash happens rarely- only once or twice.
I have no idea if this is related the main bug reported (with the build
types)- only that it provides some stacktrace into the JS, which is absent
in the usual crash scenario.

The implementation hasn’t changed in either case.
This (sonify) crash happened with ‘Run’

**Comment by soommy12** [comment]
@mardann Hmm, I can't say more about that sonify error. that didn't happen during our tests. When it comes to gson matter - we're looking for a proper solution.

**Comment by mardann** [comment]
Thanks for the update.
We are still waiting on the fix.
I’d be glad to offer a “debug session” as to reproduce and track this bug
properly on both our sides.

**Comment by soommy12** [comment]
Hi @mardann! The update is on its way. It is the best moment to introduce the fix but we still don't have enough information about the bug. Would be great to hear more about this problem. Any feedback will be appreciated!

**Comment by mardann** [comment]
Hey, thanks for the update. Everything I know about this bug is posted in this thread. 
Have you been able to reproduce it with the APK I sent you?

**Comment by soommy12** [comment]
No, we didn't meet any problem with that apk. Still trying to figure it out.

**Comment by mardann** [comment]
So - you were able to open the app we sent you, and navigate to pages with "highcharts" and view them without any problems?
