### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to com.highsoft.highcharts.Common.HIColor

### ISSUE THREAD

**Issue by adirahman** [highcharts/highcharts-android#16]
java.lang.ClassCastException: java.lang.String cannot be cast to com.highsoft.highcharts.Common.HIColor
        at com.highsoft.highcharts.Common.HIChartsClasses.HIColumn.getParams(SourceFile:326)
        at com.highsoft.highcharts.Common.HIChartsClasses.HIOptions.getParams(SourceFile:582)
        at com.highsoft.highcharts.Core.HIChartView.b(SourceFile:242)
        at com.highsoft.highcharts.Core.HIChartView.reload(SourceFile:257)
        at monitoring_analytic.cartenz.com.landing.category.penerimaan.progressCapaianTarget.ProgressCapaianTargetFragment.updateChart(ProgressCapaianTargetFragment.java:274)
        at monitoring_analytic.cartenz.com.landing.category.penerimaan.progressCapaianTarget.ProgressCapaianTargetFragment.getDataResponse(ProgressCapaianTargetFragment.java:282)
        at cartenz.com.tax_analytics_network.potensi.RepoPotensi$14.onResponse(RepoPotensi.java:379)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6361)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by adirahman** [comment]
The Code is:
HIColumn series1 = new HIColumn();
        series1.setName("Realisa");
        ArrayList<HIColor> listColor = new ArrayList<>();
        series1.setColor(HIColor.initWithHexValue("f7423C"));
        ArrayList<Number> listDataSeries1 = new ArrayList<>();
        for (int i = 0; i < listData.size(); i++) {
            if(listData.get(i).color.equals("blue")){
                listColor.add(HIColor.initWithHexValue("3f89df"));
            }else if (listData.get(i).color.equals("yellow")){
                listColor.add(HIColor.initWithHexValue("ffad48"));
            }
            listDataSeries1.add(listData.get(i).realisasi_simplified);
        }
        series1.setColors(listColor);
        series1.setData(listDataSeries1);
        series1.setPointPadding(0.2);
        series1.setPointPlacement(-0.2);

**Comment by soommy12** [comment]
Hello @adirahman , thanks for your report. It is a small bug, it will be fixed in the next release. For now, I can suggest setting your colours in `options` as a workaround:
`options.setColors(listColors);`

**Comment by adirahman** [comment]
even if i has 2 coloumn data? put it in options?

**Comment by adirahman** [comment]
yes, that's right, is it possible?

**Comment by soommy12** [comment]
Yes, it is. You need to set **HIMarker** for the specific point. Check the solutions here #13

**Comment by adirahman** [comment]
i using marker but still not appear the yellow

HIColumn series1 = new HIColumn();
    series1.setName("Realisasi");
    ArrayList<HashMap<String,Object>> listDataFromApi = new ArrayList<>();
	 for (int i = 0; i < listData.size(); i++) {
            HashMap<String, Object> map = new HashMap<>();
            map.put("y",listData.get(i).realisasi_simplified);
            HIMarker marker = new HIMarker();
            if(listData.get(i).color.equals("blue")){
                HIColor blue = HIColor.initWithHexValue("3f89df");
                marker.setColor(blue);
            }else if (listData.get(i).color.equals("yellow")){
                HIColor yellow = HIColor.initWithHexValue("ffad48");
                marker.setColor(yellow);
            }
            map.put("marker",marker);
            listDataFromApi.add(map);
        }
   
    
    series1.setData(listDataFromApi);
    series1.setPointPadding(0.2);
    series1.setPointPlacement(-0.2);
	
	HIColumn series3 = new HIColumn();
    series3.setName("Target Realisasi");
    series3.setColor(HIColor.initWithHexValue("f3f3f3"));
    ArrayList<Float> listDataSeries3 = new ArrayList<>();
    for (int i = 0; i < listData.size(); i++) {
        listDataSeries3.add(listData.get(i).target_simplified);
    }
    series3.setData(listDataSeries3);
    series3.setPointPadding(0.4);
    series3.setPointPlacement(-0.2);
	
	 ArrayList<HISeries> listSeries = new ArrayList<>();
    listSeries.add(series1);
    listSeries.add(series3);
    options.setSeries(listSeries);

**Comment by soommy12** [comment]
Ah, sorry I've made mistake. Markers don't apply to column series. If you want your columns from one series to have different colours you should use **HIData** and _setColor()_ method. Check out this:
```
        ArrayList<HIData> listDataFromApi = new ArrayList<>();
        for (int i = 0; i < listData.size(); i++) {
            HIData data = new HIData();
            data.setY(listData.get(i).realisasi_simplified);
            if(listData.get(i).color.equals("blue")){
                HIColor blue = HIColor.initWithHexValue("3f89df");
                data.setColor(blue);

            }else if (listData.get(i).color.equals("yellow")){
                HIColor yellow = HIColor.initWithHexValue("ffad48");
                data.setColor(yellow);
            }
            listDataFromApi.add(data);
        }
        series1.setData(listDataFromApi);
```

**Comment by adirahman** [comment]
Okay, done, work's like charm,

Thank's a lot @soommy12
