### ISSUE TITLE
SDK 24, AsyncInflater, crash

### ISSUE THREAD

**Issue by georrge1994** [highcharts/highcharts-android#190]
`[main] Uncaught exception from Thread[main,5,main] is:
    java.lang.IllegalStateException: Calling View methods on another thread than the UI thread.
    	at com.android.webview.chromium.WebViewChromium.b(chromium-Monochrome.aab-stable-438910523:2) ~[na:na]
    	at com.android.webview.chromium.WebViewChromium.init(chromium-Monochrome.aab-stable-438910523:15) ~[na:na]
    	at android.webkit.WebView.<init>(WebView.java:696) ~[na:0.0]
    	at android.webkit.WebView.<init>(WebView.java:631) ~[na:0.0]
    	at android.webkit.WebView.<init>(WebView.java:614) ~[na:0.0]
    	at android.webkit.WebView.<init>(WebView.java:601) ~[na:0.0]
    	at android.webkit.WebView.<init>(WebView.java:591) ~[na:0.0]
    	at com.highsoft.highcharts.Core.HIChartView.a(SourceFile:105) ~[na:0.0]
    	at com.highsoft.highcharts.Core.HIChartView.<init>(SourceFile:99) ~[na:0.0]
    	at java.lang.reflect.Constructor.newInstance0(Native Method) ~[na:0.0]
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:430) ~[na:0.0]
    	at android.view.LayoutInflater.createView(LayoutInflater.java:645) ~[na:0.0]
    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) ~[na:0.0]
    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) ~[na:0.0]
    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) ~[na:0.0]
    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) ~[na:0.0]
    	at android.view.LayoutInflater.inflate(LayoutInflater.java:518) ~[na:0.0]
    	at android.view.LayoutInflater.inflate(LayoutInflater.java:426) ~[na:0.0]
    	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.runInner(AsyncLayoutInflater.java:188) ~[na:0.0]
    	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(AsyncLayoutInflater.java:202) ~[na:0.0]`

We use async inflating for recycler view and highcharts is a part of viewHodler. SDK 24 got a constantly crash, and we totally know, that inflating is correct. Seems your libs has a problem with threading inside, please fix it.

**Comment by soommy12** [comment]
Hi @georrge1994 ! Thank you for your question. That issue is connected with WebView 39 version. Please, take steps which were discussed here: https://github.com/highcharts/highcharts-android/issues/115
