### ISSUE TITLE
Inflate HIChartView in Fragment

### ISSUE THREAD

**Issue by VopRos-ZP** [highcharts/highcharts-android#277]
android.view.InflateException: Binary XML file line #14 in layout/fragment_metrics: Binary XML file line #14 in layout/fragment_metrics: Error inflating class com.highsoft.highcharts.core.HIChartView
Caused by: android.view.InflateException: Binary XML file line #14 in :layout/fragment_metrics: Error inflating class com.highsoft.highcharts.core.HIChartView
Caused by: java.lang.ClassCastException: dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper cannot be cast to android.app.Activity
at com.highsoft.highcharts.core.HIChartView.<init>

I use Hilt and Fragment and latest lib version (11.4.0)

Example:

*XML*:
```xml
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.highsoft.highcharts.core.HIChartView
        android:id="@+id/hiChart"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

*MetricsFragment*:

```kt
@AndroidEntryPoint
class MetricsFragment : BaseFragment<FragmentMetricsBinding>(R.layout.fragment_metrics) {

    override val binding by lazy { FragmentMetricsBinding.bind(baseView) }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        binding.hiChart.apply {
            val options = HIOptions()
            val chart = HIChart()
            chart.type = "column"
            options.chart = chart

            val title = HITitle()
            title.text = "Demo chart"
            options.title = title

            val series = HIColumn()
            series.data = ArrayList<Number>(
                mutableListOf(
                    49.9,
                    71.5,
                    106.4,
                    129.2,
                    144,
                    176,
                    135.6,
                    148.5,
                    216.4,
                    194.1,
                    95.6,
                    54.4
                )
            )
            options.series = ArrayList(listOf(series))
            setOptions(options)
        }
    }

}
```

BaseFragment extends Fragment

**Comment by VopRos-ZP** [comment]
Yes, parent Activity annotated with @AndroidEntryPoint
My BaseFragment:
```kt
abstract class BaseFragment<T: ViewBinding>(
    private val layout: Int
) : Fragment() {

    protected lateinit var baseView: View
    protected abstract val binding: T

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        baseView = inflater.inflate(layout, container, false)
        return baseView
    }

    protected val verticalLayoutManager by lazy { LinearLayoutManager(requireContext(), LinearLayoutManager.VERTICAL, false) }

}
```

**Comment by VopRos-ZP** [comment]
Im trying your method for getting LayoutInflater use:
```kt
override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        baseView = LayoutInflater.from(requireContext()).inflate(layout, container, false)
        return baseView
    }
```
But its showing
`
Caused by: java.lang.ClassCastException: dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper cannot be cast to android.app.Activity
                                                                                                    	at com.highsoft.highcharts.core.HIChartView.<init>(SourceFile:116)`
And old error

**Comment by MikolajMichalczak** [comment]
@VopRos-ZP Could you please try with `requireActivity()` instead of `requireContext()`?
However it is indeed a bug and it will be fixed in the upcoming release. If this workaround does not work for you please stay tuned.

**Comment by VopRos-ZP** [comment]
New exception:

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
at com.highsoft.highcharts.core.i.a(SourceFile:34)
                 	at com.highsoft.highcharts.core.f.c(SourceFile:103)
                 	at com.highsoft.highcharts.core.HIChartView.a(SourceFile:357)
                 	at com.highsoft.highcharts.core.HIChartView.onDraw(SourceFile:304)
                 	at android.view.View.draw(View.java:23012)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21880)
                 	at android.view.View.draw(View.java:22738)
                 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
                 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
                 	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21871)
                 	at android.view.View.draw(View.java:22738)
                 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
                 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21871)
                 	at android.view.View.draw(View.java:22738)
                 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
                 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
                 	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21871)
                 	at android.view.View.draw(View.java:22738)
                 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
                 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21871)
                 	at android.view.View.draw(View.java:22738)
                 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
                 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
                 	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21871)
                 	at android.view.View.draw(View.java:22738)
                 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
                 	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
                 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21871)
                 	at android.view.View.draw(View.java:22738)
                 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
                 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21871)
                 	at android.view.View.draw(View.java:22738)
                 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
                 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21871)
                 	at android.view.View.draw(View.java:22738)
                 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
                 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21871)
                 	at android.view.View.draw(View.java:22738)
                 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
                 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21871)
                 	at android.view.View.draw(View.java:22738)
                 	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
                 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
                 	at android.view.View.draw(View.java:23016)
                 	at com.android.internal.policy.DecorView.draw(DecorView.java:887)
                 	at android.view.View.updateDisplayListIfDirty(View.java:21880)
                 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
                 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)
                 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)
                 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4645)
                 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4363)
                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3474)
                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2265)
     	                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9009)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:946)
                 	at android.view.Choreographer.doFrame(Choreographer.java:875)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:210)
                 	at android.os.Looper.loop(Looper.java:299)
                 	at android.app.ActivityThread.main(ActivityThread.java:8250)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.GsonBuilder" on path: DexPathList[[dex file "/data/data/ru.cityron/code_cache/.overlay/base.apk/classes11.dex", dex file "/data/data/ru.cityron/code_cache/.overlay/base.apk/classes15.dex", dex file "/data/data/ru.cityron/code_cache/.overlay/base.apk/classes17.dex", dex file "/data/data/ru.cityron/code_cache/.overlay/base.apk/classes7.dex", dex file "/data/data/ru.cityron/code_cache/.overlay/base.apk/classes8.dex", zip file "/data/app/~~SftiTJ5JDFFw8VAM0CmcEA==/ru.cityron-Knr2bt7bF5TFZ3FSQOBRgA==/base.apk"],nativeLibraryDirectories=[/data/app/~~SftiTJ5JDFFw8VAM0CmcEA==/ru.cityron-Knr2bt7bF5TFZ3FSQOBRgA==/lib/arm64, /system/lib64, /system_ext/lib64]]
                 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)

**Comment by VopRos-ZP** [comment]
Now its work, thx
