### ISSUE TITLE
JSON error in HIFunction events.legendItemClick

### ISSUE THREAD

**Issue by shanselm-ergon** [highcharts/highcharts-android#282]
Hello Highcharts

Since Highcharts 11.4.1, we encounter the following error:
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 98 column 40 path $.series[0].events.legendItemClick
    	at com.google.gson.Gson.fromJson(Gson.java:1241)
    	at com.google.gson.Gson.fromJson(Gson.java:1137)
    	at com.google.gson.Gson.fromJson(Gson.java:1047)
    	at com.google.gson.Gson.fromJson(Gson.java:982)
    	at com.highsoft.highcharts.core.HIChartView.onSizeChanged(SourceFile:210)
...
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 98 column 40 path $.series[0].events.legendItemClick
    	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
    	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:500)
    	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:422)
    	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:779)
    	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725)
    	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007)
    	at com.google.gson.Gson.fromJson(Gson.java:1227)
```

The error occurs while loading the chart, not while interacting with it. 

In our code (Kotlin) we have a series, on the series we add the following event listener:
```
HIEvents().apply {
     legendItemClick = HIFunction("function() { return false; }")
}
```
I also tried with a native function, but same result:
```
HIEvents().apply {
     legendItemClick = HIFunction {}
}
```
Our code is in place for four years now, without problems, so I guess something has changed in Highcharts 11.

Thanks for your help.

**Comment by MikolajMichalczak** [comment]
Hi @shanselm-ergon,
Thank you for bringing this bug to our attention. We are currently working on a fix, and we hope to have it resolved in the upcoming release. Stay tuned!

**Comment by MikolajMichalczak** [comment]
@shanselm-ergon  Version 11.4.3 has been released and is now available.

**Comment by MikolajMichalczak** [comment]
Closing due to inactivity. Please feel free to reopen the ticket if you have any further questions.
