### ISSUE TITLE
Crash when attempting to set HIOptions.colors

### ISSUE THREAD

**Issue by DanGTZ** [highcharts/highcharts-android#3]
## Device
Nexus 6 API 27 Emulator

## Code that produce the crash (if commented there is no crash and chart is displayed)
```
options.colors = new ArrayList<>();
options.colors.add(HIColor.initWithRGB(255, 0, 0));
options.colors.add(HIColor.initWithRGB(0, 0, 255));
```

## Stack trace
```
java.lang.ClassCastException: java.lang.String cannot be cast to com.highsoft.highcharts.Common.HIColor
                                                                  at com.highsoft.highcharts.Common.HIChartsClasses.HIOptions.getParams(HIOptions.java:363)
                                                                  at com.highsoft.highcharts.Core.HIChartView.loadChartHtml(HIChartView.java:206)
                                                                  at com.highsoft.highcharts.Core.HIChartView.onDraw(HIChartView.java:184)
                                                                  at android.view.View.draw(View.java:19192)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:18142)
                                                                  at android.view.View.draw(View.java:18920)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                                                                  at android.view.View.draw(View.java:19195)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:18142)
                                                                  at android.view.View.draw(View.java:18920)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:18133)
                                                                  at android.view.View.draw(View.java:18920)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                                                                  at android.view.View.draw(View.java:19195)
                                                                  at android.widget.ScrollView.draw(ScrollView.java:1739)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:18142)
                                                                  at android.view.View.draw(View.java:18920)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:18133)
                                                                  at android.view.View.draw(View.java:18920)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:18133)
                                                                  at android.view.View.draw(View.java:18920)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:18133)
                                                                  at android.view.View.draw(View.java:18920)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:18133)
                                                                  at android.view.View.draw(View.java:18920)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
                                                                  at android.view.View.draw(View.java:19195)
                                                                  at com.android.internal.policy.DecorView.draw(DecorView.java:788)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:18142)
                                                                  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
                                                                  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
                                                                  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
                                                                  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
                                                                  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                  at android.os.Handler.handleCallback(Handler.java:790)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by soommy12** [comment]
Hi @DanGTZ ! Thank you for reporting a bug. The problem was HIColor object was changing to Javascript representation in the wrapper too early. I've made a fix in the library. Please download the new _aar_ and try your code out again.
