### ISSUE TITLE
How to add arrayList object to HighCharts

### ISSUE THREAD

**Issue by abhishekhzb** [highcharts/highcharts-android#5]
**I am using ** https://www.highcharts.com/android/demo/column-rotated-labels 
As documentation data added as  below 
```
        Object[] object1 = new Object[] { "Shanghai", 23.7 };
        Object[] object2 = new Object[] { "Lagos", 16.1 };
        Object[] object3 = new Object[] { "Istanbul", 14.2 };
        Object[] object4 = new Object[] { "Karachi", 14 };
        Object[] object5 = new Object[] { "Mumbai", 12.5 };

       series1.data = new ArrayList<>(Arrays.asList(object1, object2, object3, object4, object5));
```
What i want to add 
```
` ArrayList<Top_10_BouquitShowPojo> myList = new ArrayList<>();
        Top_10_BouquitShowPojo list = new Top_10_BouquitShowPojo("Abhishek",27);
         myList .add(new Top_10_BouquitShowPojo("Shanghai",23.7));
        myList .add(new Top_10_BouquitShowPojo("Lagos",16.1 ));
        myList .add(new Top_10_BouquitShowPojo("Mumbai",75));
        myList .add(new Top_10_BouquitShowPojo("Delhi",16.1 ));`

i want to add myList , Please help me how can i add this.
```

**Comment by soommy12** [comment]
Hi @abhishekhzb,

Highcharts serializes data which are in ArrayList or data which is ArrayList itself. There are few options to achieve what you've asked about then:

**1.** Stick to the style which were provided in example you posted.
**2.** Provide ArrayList of Object[] type like this:
```
ArrayList<Object[]> myList1 = new ArrayList<>();
myList1.add(new Object[] {"Shanghai", 21} );
myList1.add(new Object[] {"Lagos", 16.1 } );
myList1.add(new Object[] {"Istanbul", 14.2} );
myList1.add(new Object[] {"Karachi", 14} );
column1.data = myList1;
```
**3.** Extend your class by ArrayList to make it behave like one:
```
public class Foo extends ArrayList<Object> {
    private String str;
    private Number nr;

    public Foo(String str, Number nr){
        this.str = str;
        this.nr = nr;
        add(str);
        add(nr);
    }
}
```
Keep in mind to add variables in the right order! And then:
```
ArrayList<Foo> myList2 = new ArrayList<>();
myList2.add(new Foo("Shanghai", 23.7));
myList2.add(new Foo("Lagos", 16.1 ));
myList2.add(new Foo("Istanbul", 14.2));
myList2.add(new Foo("Karachi", 14));
column1.data = myList2;
```

**Comment by abhishekhzb** [comment]
Thanks for your reply, One more issue i'm facing from yesterday , I am using Highcharts graph inside fragment , when fragments starts i'm hitting an API when API response coming with success then i'm starting highcharts graph.  I have noticed that if little bit delay to start hightcharts graph then i'm getting RunTime Exception as below 


` FATAL EXCEPTION: main
                                                                        Process: com.kabloom.kabloomims, PID: 22822
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map com.highsoft.highcharts.Common.HIChartsClasses.HIOptions.getParams()' on a null object reference
                                                                            at com.highsoft.highcharts.Core.HIChartView.a(SourceFile:208)
                                                                            at com.highsoft.highcharts.Core.HIChartView.onDraw(SourceFile:186)
                                                                            at android.view.View.draw(View.java:17201)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16183)
                                                                            at android.view.View.draw(View.java:16967`

**Comment by soommy12** [comment]
Can you provide your code? Sounds like you try to refer to value which was not assigned. You can check how charts are managed in fragments in the example app [here](https://github.com/highcharts/highcharts-android/blob/master/Example/HighFit/app/src/main/java/com/highsoft/highfit/DashboardFragment.java) also.

**Comment by abhishekhzb** [comment]
what i 'm doing is When Fragments creates , if Internet Connection is available it will call a method of JSON request , if success message will come it will call method of graph, now i'm calling only from json request method, if i am calling method when activity starts it works file , when using as below code app crashes.
I also checked one thing i i put only xml code to fragment.xml , No Java Code then it starts crashing. 

Fragment Code Here 
```

 package com.kabl.kab.fragments;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.TextView;

import com.android.volley.DefaultRetryPolicy;
import com.android.volley.Request;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.StringRequest;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.highsoft.highcharts.Common.HIChartsClasses.HIChart;
import com.highsoft.highcharts.Common.HIChartsClasses.HIColumn;
import com.highsoft.highcharts.Common.HIChartsClasses.HICondition;
import com.highsoft.highcharts.Common.HIChartsClasses.HIDataLabels;
import com.highsoft.highcharts.Common.HIChartsClasses.HILabel;
import com.highsoft.highcharts.Common.HIChartsClasses.HILabels;
import com.highsoft.highcharts.Common.HIChartsClasses.HILegend;
import com.highsoft.highcharts.Common.HIChartsClasses.HILine;
import com.highsoft.highcharts.Common.HIChartsClasses.HIOptions;
import com.highsoft.highcharts.Common.HIChartsClasses.HIPlotOptions;
import com.highsoft.highcharts.Common.HIChartsClasses.HIResponsive;
import com.highsoft.highcharts.Common.HIChartsClasses.HIRules;
import com.highsoft.highcharts.Common.HIChartsClasses.HISeries;
import com.highsoft.highcharts.Common.HIChartsClasses.HIStyle;
import com.highsoft.highcharts.Common.HIChartsClasses.HISubtitle;
import com.highsoft.highcharts.Common.HIChartsClasses.HITitle;
import com.highsoft.highcharts.Common.HIChartsClasses.HITooltip;
import com.highsoft.highcharts.Common.HIChartsClasses.HIXAxis;
import com.highsoft.highcharts.Common.HIChartsClasses.HIYAxis;
import com.highsoft.highcharts.Common.HIColor;
import com.highsoft.highcharts.Core.HIChartView;
import com.kabloom.kabloomims.R;
import com.kabloom.kabloomims.network_class.AppController;
import com.kabloom.kabloomims.pojo.DashBoardSpinner;
import com.kabloom.kabloomims.pojo.high_velocity.HighVelocityPojo;
import com.kabloom.kabloomims.pojo.high_velocity.Top_10_BouquitShowPojo;
import com.kabloom.kabloomims.utils.Constants;
import com.kabloom.kabloomims.utils.ProjectUtils;

import org.json.JSONArray;
import org.json.JSONException;
import org.w3c.dom.Text;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;

/**
 * A simple {@link Fragment} subclass.
 */
public class Top_10_Bouquet extends Fragment {
    private Bundle bundle;
    private ProjectUtils utils;
    String whareHouse,time,whareHouseName,timeName;
    private static final String TAG = "Top_10_Bouquet";
    TextView whareHNameTv,timeNameTv;
    private static final int MY_SOCKET_TIMEOUT_MS = 60000;
    List<HighVelocityPojo> mList;
    HIChartView chartView;


    public Top_10_Bouquet() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_top_10__bouquet, container, false);
        //Views
        whareHNameTv = (TextView)view.findViewById(R.id.whareHN_10B);
        timeNameTv = (TextView)view.findViewById(R.id.timeName_10B);
        chartView = (HIChartView) view.findViewById(R.id.hc_10_Bouquet);

        utils = new ProjectUtils(getActivity());
 



        if (utils.haveNetworkConnection()) {
            JsonRequestGraph();
        }else {
            utils.showtoast("Internet Connection Not Available");
        }




        return view;
    }

    

    private void JsonRequestGraph() {
        utils.showDialog();

        String url = Constants.TOP_10_BOUQUIT+"days="+time+"&warehouse_id="+whareHouse;
        Log.e("URL", "" + url);


        StringRequest eventoReq = new StringRequest(Request.Method.GET, url,
                new Response.Listener<String>() {
                    @Override
                    public void onResponse(String response) {
                        Log.e("RESPONSE", response.toString());

                        utils.hideDialog();
                        try {
                            JSONArray j = new JSONArray(response);

                            Gson gson = new Gson();
                            Type listType = new TypeToken<List<HighVelocityPojo>>() {
                            }.getType();
                             mList  = gson.fromJson(response.toString(), listType);

                            callGraphView(); // calling graph

                        } catch (JSONException e) {
                            e.printStackTrace();
                        }


                    }
                }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                Log.e("Error: ", "" + error.getMessage());
                utils.hideDialog();
                utils.showtoast("Please try again...");

            }
        });

        eventoReq.setRetryPolicy(new DefaultRetryPolicy(
                MY_SOCKET_TIMEOUT_MS,
                DefaultRetryPolicy.DEFAULT_MAX_RETRIES,
                DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));
        AppController.getInstance(getContext()).addToRequestQueue(eventoReq);


    }


private void callGraphView() {

        HIOptions options = new HIOptions();

        HIChart chart = new HIChart();
        chart.type = "column";
        options.chart = chart;

        HITitle title = new HITitle();
        title.text = "KaBloom Top 10 Bouquet";
        options.title = title;

        HIXAxis xAxis = new HIXAxis();
        xAxis.type = "category";
        xAxis.labels = new HILabels();
        xAxis.labels.rotation = -45;
        xAxis.labels.style = new HIStyle();
        xAxis.labels.style.fontSize = "13px";
        xAxis.labels.style.fontFamily = "Verdana, sans-serif";
        options.xAxis = new ArrayList<HIXAxis>(){{add(xAxis);}};

        HIYAxis yAxis = new HIYAxis();
        yAxis.min = 0;
        yAxis.title = new HITitle();
        yAxis.title.text = "Velocity";
        options.yAxis = new ArrayList<HIYAxis>(){{add(yAxis);}};

        HILegend legend = new HILegend();
        legend.enabled = false;
        options.legend = legend;

        HITooltip tooltip = new HITooltip();
        tooltip.pointFormat = "Population in'2008': <b>{point.y:.1f} millions</b>";
        options.tooltip = tooltip;

        HIColumn series1 = new HIColumn();
        series1.name = "Population";

        ArrayList<Top_10_BouquitShowPojo> myList2 = new ArrayList<>();
        myList2.add(new Top_10_BouquitShowPojo("Shanghai", 23.7));
        myList2.add(new Top_10_BouquitShowPojo("Lagos", 16.1 ));
        myList2.add(new Top_10_BouquitShowPojo("Istanbul", 14.2));
        myList2.add(new Top_10_BouquitShowPojo("Karachi", 14));

        series1.data = myList2;

        series1.dataLabels = new HIDataLabels();
        series1.dataLabels.enabled = true;
        series1.dataLabels.rotation = -90;
        series1.dataLabels.color = HIColor.initWithHexValue("FFFFFF");
        series1.dataLabels.align = "right";
        series1.dataLabels.format = "{point.y:.1f}";
        series1.dataLabels.y = 10;
        series1.dataLabels.style = new HIStyle();
        series1.dataLabels.style.fontSize = "13px";
        series1.dataLabels.style.fontFamily = "Verdana, sans-serif";
        options.series = new ArrayList<>(Arrays.asList(series1));
        chartView.options = options;
    }


}

```

**Comment by soommy12** [comment]
The chart try to draw itself before your call to the other API. Try to add **chartView** inside _callGraphView()_ method or use the `chartView.setWillNotDraw(true);` just after `findViewById()` and inside your method change it to the false so the chart will draw in the right time. This management is showed in the example app. Please consider to analyse it.

**Comment by abhishekhzb** [comment]
In the above code i added as your suggestion, The app is running not crashing but nothing is showing , blank white screen is coming.
```

 @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_top_10__bouquet, container, false);
        //Views
        chartView = (HIChartView) view.findViewById(R.id.hc_10_Bouquet);
        chartView.setWillNotDraw(true); 
        .....
       return view;
}

```
and inside graphViewCall added

```
 private void callGraphView() {
        chartView.setWillNotDraw(true);
        ......
}
```

**Comment by soommy12** [comment]
The options of the chart needs to be set in the same place when the app is calling chart view by `findViewById`. HIChartView `onDraw` method is processing those options. If the app will try to draw chart view before options are set you will get the null pointer exception. If you have **MainActivity** with the HIChartView in it's corresponding xml file but you refer to this in the fragment it won't work. Does your **StringRequest** working? Becouse it is the place where you setting the options. I called your method like this (having views in the proper xml files):
```
chartView = view.findViewById(R.id.hc_10_Bouquet);
callGraphView();
```
and it worked. It's rather wrong place when you put your xml view or problem with that request.

**Comment by abhishekhzb** [comment]
I checked its working now , Problem with my JSON Request code, that method was not calling. 
Thanks for your Help.

**Comment by soommy12** [comment]
@abhishekhzb can I close the issue and mark it as questions as it's not the library case?

**Comment by abhishekhzb** [comment]
You can close it , but one thing help me over here is that 
When we do not want to show graph we can use chartView.setWillNotDraw(true);
When we want to show use chartView.setWillNotDraw(false);

**Comment by abhishekhzb** [comment]
Hello, @soommy12  , One more issue i'm facing 
I am using this graph https://www.highcharts.com/android/demo/line-time-series

I have data in arrayList , if needed i can put it in array too instead of ArrayList 
    ArrayList<Integer> count = new ArrayList<>();
    ArrayList<String>  intervals = new ArrayList<>();

How can i add these data to **line-time-series** graph. Please help me.
